In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pyarrow

In [3]:
rideshares = pd.read_parquet(r'C:\Users\EvanSpiller\Documents\DS BootCamp\Capstone\data\HVFHV_Compressed\Combined\full_compressed_HVFHV_2019_2020.parquet')

In [12]:
rideshares2019Q4morning = rideshares.loc[
    (
       ((rideshares['Month'] == 10) |(rideshares['Month'] == 11) | (rideshares['Month'] == 12)) &
    ((rideshares['Year'] == 2019) | (rideshares['Year'] == 2022))
     & ((rideshares['Hour']>=7) & (rideshares['Hour']<=10))
    )
]

In [17]:
rideshares = pd.read_parquet(r'C:\Users\EvanSpiller\Documents\DS BootCamp\Capstone\data\HVFHV_Compressed\Combined\full_compressed_HVFHV_2022_2023')
rideshares2022Q4morning = rideshares.loc[
    (
       ((rideshares['Month'] == 10) |(rideshares['Month'] == 11) | (rideshares['Month'] == 12)) &
    ((rideshares['Year'] == 2019) | (rideshares['Year'] == 2022))
     & ((rideshares['Hour']>=7) & (rideshares['Hour']<=10))
    )
]

In [45]:
morningcommutesq420192022 = pd.concat([rideshares2022Q4morning, rideshares2019Q4morning], axis=0)

In [25]:
zones.columns

Index(['LocationID', 'Borough', 'Zone', 'service_zone'], dtype='object')

In [23]:
zones = pd.read_csv(r'C:\Users\EvanSpiller\Documents\DS BootCamp\Capstone\data\taxi+_zone_lookup.csv')

In [46]:
morningcommutesq420192022 = pd.merge(morningcommutesq420192022, zones, left_on='DOLocationID', right_on='LocationID', how='inner')

In [47]:
morningcommutesq420192022manhattan = morningcommutesq420192022.loc[morningcommutesq420192022['Borough']=='Manhattan',:]

In [33]:
morningcommutesq420192022manhattan

,PULocationID,DOLocationID,Year,Month,Day,Hour,trip_miles_sum,congestion_surcharge_sum,tips_sum,driver_pay_sum,trips,LocationID,Borough,Zone,service_zone
22045,4,1,2022,10,1,7,15.730,0.00,3.00,42.05,1,4,Manhattan,Alphabet City,Yellow Zone
22046,4,1,2022,10,1,8,28.266,0.00,5.00,70.16,2,4,Manhattan,Alphabet City,Yellow Zone
22047,4,1,2022,10,1,9,14.600,0.00,15.38,38.58,1,4,Manhattan,Alphabet City,Yellow Zone
22048,4,1,2022,10,2,7,13.870,0.00,0.00,34.65,1,4,Manhattan,Alphabet City,Yellow Zone
22049,4,1,2022,10,2,8,30.590,0.00,0.00,74.59,2,4,Manhattan,Alphabet City,Yellow Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6944496,263,265,2019,12,31,9,67.093,8.25,12.69,140.38,3,263,Manhattan,Yorkville West,Yellow Zone
6944497,263,265,2019,12,31,10,36.597,5.50,0.00,73.75,2,263,Manhattan,Yorkville West,Yellow Zone
6945735,105,255,2019,11,8,8,4.130,0.75,0.00,0.00,1,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
6945736,105,45,2019,12,6,10,1.430,2.75,1.00,8.46,1,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
6945737,105,132,2019,12,24,8,26.860,0.00,9.00,70.60,1,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone

In [48]:
groupby = morningcommutesq420192022manhattan.groupby(['PULocationID','Year'])['trips'].sum()

In [49]:
groupby = groupby.unstack()

In [50]:
groupby = groupby.reset_index()

In [51]:
groupby.to_csv(r'C:\Users\EvanSpiller\Documents\DS BootCamp\Capstone\data\morningcommutestomanhattanq4comparison.csv', index=False)